config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  resources :blogs, except: [:destroy]

  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up
    end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received

    resources :pages
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :vehicle_types, except: [:destroy]
    resources :blogs, except: [:destroy]
    resources :locations
    resources :change_destination_requests
    resources :shipments do
      member do
        delete :cancel
      end
      collection do
        post :get_bulk_coordinates
      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do
    collection do   
    post :get_all_drivers
  end end


    resources :payments
  end
  namespace :cargo do
    root 'dashboard#index'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :ongoing
        post :calculate_fare
        get :upcoming
        get :completed
        post :get_bulk_coordinates
      end
      member do
        get :get_coordinates
        get :cancel
        get :update_destination
        patch :update_destination
      end
    end
    resources :bids do
      member do
        post :accept
        post :reject
      end
    end
    resources :dashboard , only: [:index]
  end
  namespace :fleet do
    root 'shipments#posted'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :active
        get :ongoing
        get :won
        get :completed
      end
      member do
        get :quit_bid
        get :assign_vehicle
        get :cancel
        get :get_coordinates
        post :not_interested
      end
      resources :bids do
        collection do
          post :bid_details
          get :bidNow
          # get :notInterested
        end
      end
    end
    
    resources :drivers do
      collection do
        post :register_as_driver
      end
    end
    resources :vehicles do
      collection do
        get :vehicle_types
     
    end
      member do
        post :change_driver
        get :change_driver
      end
    end

    resources :dashboard , only: [:index]
  end
  resources :countries do
    collection do
      get "location/:location_id" => "countries#location"
      get :get_vehicles_by_country
      # get :vehicles
    end
  end
  devise_for :users, controllers: {:invitations => 'users/invitations',passwords: 'users/passwords', sessions: 'users/sessions', registrations: 'users/registrations',confirmations: 'users/confirmations'   }

  devise_scope :user do
    # match "user/account" => "user#account", as: :user_account, via: [:get, :post]
    match '/users/mobile-verification' => 'users/registrations#mobile_verification' , via: [:get, :post]
    get '/users/send-verification-code/:user_id' => 'users/registrations#send_verification_code', as: :send_verification_code
    match '/sign_up' => "users/registrations#new", as: :sign_up,via: [:get, :post]
  end

  resources :companies, :only => [  ] do
    collection do
      post :add_company_information
      patch :add_company_information
      post :add_individual_information
      patch :add_individual_information
      get :edit
      get :get_individual_information
      get :get_company_information
      put :presign_upload
    end
  end
  match "/ratings" => "rating#rate", via: [:get, :post] , as: :ratings_shipment
  resources :invoices , only: [:show]

  namespace :api do
  	namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions', registrations: 'api/v1/users/registrations'  }
      resources :ratings do
      end
      resources :invoices do
        member do
          post :send_in_email
        end
      end
      namespace :cargo do
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :ongoing
              get :upcoming
              post :calculate_fare
              get :completed
            end
            resources :bids do
              member do
                post :accept
                post :reject
              end
            end
          end
        end
      end
      namespace :fleet do
        resources :drivers do
          collection do
            post :register_as_driver
            post :upcoming_shipments
            post :ongoing_shipments
            post :completed_shipments
            post :update_vehicle_status
            post :report_problem
            post :payment_received
          end
        end
        resources :vehicles do
          collection do
            get :vehicle_types
            post :change_driver
            get :fetch_nearby
          end
          member do
            put :update_lat_lng
          end
        end
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :active
              get :won
              get :ongoing
              get :ongoing_vehicles
              get :completed

            end
            member do
              post :reject_bid
              post :quit_bid
              put :update_destination
              get :vehicles
              post :not_interested
            end
          resources :bids do
            collection do
              get :bidNow
              get :notInterested
            end
          end
          end
        end
      end
	  	resources :companies, :only => [] do
        collection do
          post :add_company_information
          post :add_individual_information
          get :get_individual_information
          get :get_company_information
        end
      end
      resources :countries do
        member do
          get :locations
          get :vehicles
        end
      end
      resources :reports do
        collection do
          post :logs_report
        end
      end
      resources :email do
        collection do
          post :send_shipment_email
        end
      end
      resources :signed_urls do
        collection do
          put :presign_upload
        end
      end
      resources :users, :only => [:update, :destroy] do
        collection do
          post :send_phone_verify_code
          put :verify_phone_number
          post :resent_code

          post :register_as_fleet_owner
          post :register_as_cargo_owner
          post :register_as_individual
          post :register_as_company
          post :current_user_detail
          post :db_device_id
          post :reset_password
          patch :change_online_status
          patch :change_device_id
        end
        member do
          get :notifications
        end
      end
      get 'shipments/:shipment_id/get_bids_count', to: 'fleet/bids#get_bids_count'
    end
  end
  resources :notifications , only: [] do
    collection do
      post :mark_viewed
    end
  end
  resources :users
  resources :subscriptions
  resources :dashboard  , only: [:index] do
    collection do
      get :home
      post :home_shipment
      post :share_iphone
      post :share_android
      post :contact
      get  :privacy_policy
      get  :terms_and_conditions
    end
  end

 resources :pages
  # get "/del" => "company#del"
  root 'dashboard#home'
end

app/models/location.rb
class Location < ApplicationRecord
	audited
	belongs_to :country
	belongs_to :company

	validates :rate , presence: :true , numericality: {greater_than: 0 , message: I18n.t("greater_than_zero") }

	def contractual_locations
		"#{pickup_full_address} - #{drop_full_address} = #{try(:country).try(:currency)} #{rate.to_f}"
	end
	def pickup_full_address
		if pickup_location.include?(pickup_building_name.to_s)
			pickup_location
		else
			"#{pickup_building_name} #{pickup_location}"
		end
	end

	def drop_full_address
		if drop_location.include?(drop_building_name.to_s)
			drop_location
		else
			"#{drop_building_name} #{drop_location }"
		end
	end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController
  layout 'admin'

  # include VehicleTypeConcern

  before_action :set_location , only: [:edit, :update , :show , :destroy]
  before_action :set_location_link ,only: [:edit, :update , :show , :index]
  # before_action :set_vehicle_type, only: [:edit , :new, :create , :update]


  def index
    @locations = Location.all
  end
  def new
    @company = Company.find(params[:company_id])
    set_vehicle_type
    @location = Location.new
  end
  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to admin_cargo_contracts_path(company_id: @location.company.id) , notice: "Contract updated successfully!"
    else
      @company = Company.find(params[:location][:company_id])
      set_vehicle_type
      flash[:error] =   @location.errors.full_messages
      render :new
    end
  end
  def edit
    @company = @location.company
    set_vehicle_type
  end
  def update
    if @location.update(location_params)
      redirect_to admin_cargo_contracts_path(company_id: @location.company.id) , notice: "Contract updated successfully!"
    else
      @company = Company.find(params[:location][:company_id])
      set_vehicle_type
      render :edit
    end
  end
  def show

  end
  def destroy

  end
  private
  def set_location
    @location = Location.find(params[:id])
  end
  def set_location_link
    @locations_link = "active"
  end
  def location_params
    params.require(:location).permit(:pickup_location, :pickup_lat, :pickup_lng, :pickup_city,
                                     :drop_location, :drop_lat, :drop_lng, :drop_city,:rate,
                                     :company_id , :country_id, :pickup_building_name ,
                                     :drop_building_name , :loading_time , :unloading_time,
                                     :vehicle_type_id)
  end
  def set_vehicle_type
    @vehicle_types = VehicleType.where(:country_id => @company.owner.try(:country_id))
  end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/_form.html.erb
<div class="form-group">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :pickup_location%>
  <%=f.text_field :pickup_location , class: "form-control google_auto_complete" , placeholder: "*Pickup Location", required: true ,onFocus: call_geolocate %>
  <%=f.hidden_field :pickup_lat %>
  <%=f.hidden_field :pickup_lng %>
	<%= f.hidden_field :pickup_city%>
	<%= f.hidden_field :country_id, value: @company.owner.try(:country_id)%>
	<%= f.hidden_field :company_id, value: @company.id%>
</div>
<div class = "form-group">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :pickup_building_name %>
	<%=f.text_field :pickup_building_name , class: "form-control" , placeholder: "*Pickup building name", required: true%>
</div>
<div class="form-group">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :drop_location%>
  <%=f.text_field :drop_location , class: "form-control google_auto_complete" , placeholder: "*Dropoff Location" , requried: true,onFocus: call_geolocate  %>
  <%=f.hidden_field :drop_lat %>
  <%=f.hidden_field :drop_lng %>
	<%= f.hidden_field :drop_city%>
</div>
<div class = "form-group">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :drop_building_name %>
	<%=f.text_field :drop_building_name , class: "form-control" , placeholder: "*Drop building name ", required: true %>
</div>
<div class="form-group has-feedback">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :rate%>
  <%= f.number_field :rate, class: "form-control greater_than_zero", placeholder: "* Rate", step: :any ,required: :true %>
</div>
<div class="form-group has-feedback">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :vehicle_type_id, "Specify Type of Vehicle Required?" %>
	<%= f.collection_select :vehicle_type_id, @vehicle_types, :id, :name,{include_blank: "Specify Type of Truck Required?"},{class: "form-control" , required: true} %>
</div>
<div class="form-group has-feedback">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :unloading_time, "Unloading Time at Dropoff (Hours)" %>
	<%=f.number_field  :unloading_time , placeholder: "Unloading Time*",step: :any, class: "form-control" , required: true%>
</div>
<div class="form-group has-feedback">
	<%= f.label "*" , class: "label_required"%>
	<%= f.label :loading_time ,"Loading Time at Pickup (Hours)"%>
	<%=f.number_field  :loading_time , placeholder: "Loading Time*",step: :any,	 class: "form-control",  required: true%>
</div>
<div>
  <%= f.submit action, class: "btn btn-primary btn-block btn-flat" %>
</div>

app/views/admin/locations/edit.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Edit Contract</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
              <%= form_for @location, url: admin_location_path do |f|%>
                <%= render partial: "form", locals: {f: f, action: "Update"}%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/locations/index.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row1">
        <div class="card-body">
          <div class = "card">
            <div class = "card-header">
              <h3 class="card-title">Contracts</h3>
            </div>
            <div class = "card-body">
              <table class="table table-bordered table-striped admin_listings" data-page-length='10'>
                <thead>
                <tr>
                  <% columns = ["pickup_location", "drop_location", "rate", "country_id", "Actions"]
                     columns.each do |col|
                  %>
                    <th><%= col.humanize %></th>
                  <%end%>
                </tr>
                </thead>
                <tbody>
                <% @locations.each do |location|%>
                  <tr>
                    <td><%= location.try(:pickup_full_address) %></td>
                    <td><%= location.try(:drop_full_address) %></td>
                    <td><%= location.try(:rate) %></td>
                    <td><%= location.try(:country).try(:name).try(:humanize) %></td>
                    <td>
                      <%#= link_to "Edit", edit_admin_location_path(location), class: "btn btn-info btn-flat" %>
                    </td>
                  </tr>
                <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/locations/new.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Add Contract</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
              <%= form_for @location, url: admin_locations_path do |f|%>
                <%= render partial: "form", locals: {f: f, action: "Create"}%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>