config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  resources :blogs, except: [:destroy]

  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up
    end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received

    resources :pages
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :vehicle_types, except: [:destroy]
    resources :blogs, except: [:destroy]
    resources :locations
    resources :change_destination_requests
    resources :shipments do
      member do
        delete :cancel
      end
      collection do
        post :get_bulk_coordinates
      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do
    collection do   
    post :get_all_drivers
  end end


    resources :payments
  end
  namespace :cargo do
    root 'dashboard#index'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :ongoing
        post :calculate_fare
        get :upcoming
        get :completed
        post :get_bulk_coordinates
      end
      member do
        get :get_coordinates
        get :cancel
        get :update_destination
        patch :update_destination
      end
    end
    resources :bids do
      member do
        post :accept
        post :reject
      end
    end
    resources :dashboard , only: [:index]
  end
  namespace :fleet do
    root 'shipments#posted'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :active
        get :ongoing
        get :won
        get :completed
      end
      member do
        get :quit_bid
        get :assign_vehicle
        get :cancel
        get :get_coordinates
        post :not_interested
      end
      resources :bids do
        collection do
          post :bid_details
          get :bidNow
          # get :notInterested
        end
      end
    end
    
    resources :drivers do
      collection do
        post :register_as_driver
      end
    end
    resources :vehicles do
      collection do
        get :vehicle_types
     
    end
      member do
        post :change_driver
        get :change_driver
      end
    end

    resources :dashboard , only: [:index]
  end
  resources :countries do
    collection do
      get "location/:location_id" => "countries#location"
      get :get_vehicles_by_country
      # get :vehicles
    end
  end
  devise_for :users, controllers: {:invitations => 'users/invitations',passwords: 'users/passwords', sessions: 'users/sessions', registrations: 'users/registrations',confirmations: 'users/confirmations'   }

  devise_scope :user do
    # match "user/account" => "user#account", as: :user_account, via: [:get, :post]
    match '/users/mobile-verification' => 'users/registrations#mobile_verification' , via: [:get, :post]
    get '/users/send-verification-code/:user_id' => 'users/registrations#send_verification_code', as: :send_verification_code
    match '/sign_up' => "users/registrations#new", as: :sign_up,via: [:get, :post]
  end

  resources :companies, :only => [  ] do
    collection do
      post :add_company_information
      patch :add_company_information
      post :add_individual_information
      patch :add_individual_information
      get :edit
      get :get_individual_information
      get :get_company_information
      put :presign_upload
    end
  end
  match "/ratings" => "rating#rate", via: [:get, :post] , as: :ratings_shipment
  resources :invoices , only: [:show]

  namespace :api do
  	namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions', registrations: 'api/v1/users/registrations'  }
      resources :ratings do
      end
      resources :invoices do
        member do
          post :send_in_email
        end
      end
      namespace :cargo do
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :ongoing
              get :upcoming
              post :calculate_fare
              get :completed
            end
            resources :bids do
              member do
                post :accept
                post :reject
              end
            end
          end
        end
      end
      namespace :fleet do
        resources :drivers do
          collection do
            post :register_as_driver
            post :upcoming_shipments
            post :ongoing_shipments
            post :completed_shipments
            post :update_vehicle_status
            post :report_problem
            post :payment_received
          end
        end
        resources :vehicles do
          collection do
            get :vehicle_types
            post :change_driver
            get :fetch_nearby
          end
          member do
            put :update_lat_lng
          end
        end
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :active
              get :won
              get :ongoing
              get :ongoing_vehicles
              get :completed

            end
            member do
              post :reject_bid
              post :quit_bid
              put :update_destination
              get :vehicles
              post :not_interested
            end
          resources :bids do
            collection do
              get :bidNow
              get :notInterested
            end
          end
          end
        end
      end
	  	resources :companies, :only => [] do
        collection do
          post :add_company_information
          post :add_individual_information
          get :get_individual_information
          get :get_company_information
        end
      end
      resources :countries do
        member do
          get :locations
          get :vehicles
        end
      end
      resources :reports do
        collection do
          post :logs_report
        end
      end
      resources :email do
        collection do
          post :send_shipment_email
        end
      end
      resources :signed_urls do
        collection do
          put :presign_upload
        end
      end
      resources :users, :only => [:update, :destroy] do
        collection do
          post :send_phone_verify_code
          put :verify_phone_number
          post :resent_code

          post :register_as_fleet_owner
          post :register_as_cargo_owner
          post :register_as_individual
          post :register_as_company
          post :current_user_detail
          post :db_device_id
          post :reset_password
          patch :change_online_status
          patch :change_device_id
        end
        member do
          get :notifications
        end
      end
      get 'shipments/:shipment_id/get_bids_count', to: 'fleet/bids#get_bids_count'
    end
  end
  resources :notifications , only: [] do
    collection do
      post :mark_viewed
    end
  end
  resources :users
  resources :subscriptions
  resources :dashboard  , only: [:index] do
    collection do
      get :home
      post :home_shipment
      post :share_iphone
      post :share_android
      post :contact
      get  :privacy_policy
      get  :terms_and_conditions
    end
  end

 resources :pages
  # get "/del" => "company#del"
  root 'dashboard#home'
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  layout 'admin'

  include UserConcern
  before_action :set_user , only: [:show]
  before_action :set_users_link  , only: [:index , :show]
  before_action :check_if_super_admin , only: [:new , :create]

  def index
    @users = User.all.reverse
  end


  def get_all_drivers
    @vehicles = Vehicle.all
puts " asdfasf #{@vehicles}"
  #  @shipments = Shipment.includes(:vehicle_type,:shipment_vehicles).where(shipment_vehicles: {status: ShipmentVehicle::ONGOING_VEHICLES })
    render json: { coordinates:  get_driver_bulk_coordinates(@vehicles) }, status: :ok
  end
  
  def show
  end

  def new
    @admin_user  = User.new
  end

  def create
    country_id = params[:user][:country_id]
    initial_mobile_number = params[:user][:mobile]
    params[:user][:mobile] = make_phone_number country_id , params[:user][:mobile]
    phone_number_valid = phone_number_valid?( country_id,  params[:user][:mobile] )

    @password = params[:user][:password]
    @admin_user = User.new(admin_user_params)
    @admin_user.role = :admin

    if phone_number_valid and @admin_user.save
      UserMailer.send_admin_credentials_to_super_admin(current_user.email, @admin_user.id , @password).deliver
      redirect_to admin_users_path , :notice => "Admin created successfully!"
    else
      flash[:error] = "Invalid Phone number." unless phone_number_valid
      render :new
    end

  end

  def set_user
    @user = User.find(params[:id])
  end

  private

  def set_users_link
    @users_link= "active"
  end

  def admin_user_params
    params.require(:user).permit(:first_name, :last_name , :email, :mobile, :country_id ,:password)
  end

end

app/controllers/api/v1/users/registrations_controller.rb
class Api::V1::Users::RegistrationsController < Devise::RegistrationsController
  # Disable CSRF protection
  prepend_before_action :authenticate_scope!, only: []
  skip_before_action :verify_authenticity_token
  include UserConcern
  # Be sure to enable JSON.
  respond_to :html, :json

  def create
    make_phone_number params
  	build_resource(sign_up_params)
  	resource_saved = resource.save
  	  yield resource if block_given?
      if resource_saved
        newuser= params[:user]
        newuser_country = Country.find_by_id(params[:user][:country_id] )
        UserMailer.send_new_user_update(newuser,  newuser_country.try(:name)).deliver
    	    if resource.active_for_authentication?
    	      sign_in(resource_name, resource, store: false)
            render json: resource
          return
  	    else
  	     expire_data_after_sign_in!
  	    end
  	 end
  	   render_resource_or_errors(resource)
  end



  def update
    make_phone_number params
    resource = User.find_by_id(params[:user][:id])

    resource_updated = resource.update_attributes(account_update_params)
    if resource_updated
      sign_in resource_name, resource, bypass: true
      resource.assgin_verification_code
      resource.send_verification_code
      render json: resource
      return
    end
    render_resource_or_errors(resource)
  end

  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    yield resource if block_given?
    render nothing: true, status: json_status(resource.destroyed?)
  end

  def require_no_authentication
  end

  private

  def make_phone_number params
    country = Country.find_by_dialing_code(params[:user][:country])
    dialing_code = country.try(:dialing_code)
      
    if dialing_code.present?
      params[:user][:country_id] = country.id
      # params[:user][:mobile] = dialing_code + params[:user][:mobile].strip
    end
  end


  def resource_name
   :user
  end

end

app/controllers/api/v1/users/sessions_controller.rb
class Api::V1::Users::SessionsController < Devise::SessionsController
  require 'auth_token'
  include UserConcern
  # Disable CSRF protection
  skip_before_action :verify_authenticity_token
  skip_before_action :verify_signed_out_user 
  # Be sure to enable JSON.
  respond_to :html,:json
  
  # POST /resource/sign_in
  def create
    make_phone_number params
    @user = User.find_by_email_or_phone(params)    
    unless @user
      return render json: {error: 'Invalid credentials'}, status: :unauthorized
    end

    if @user and @user.try(:company).try(:blacklisted)
      render json: { error: 'Your account is being verified and you will be notified shortly by Lorryz Team. For any enquiries please send email to contact@lorryz.com or call 052 1250605' },status: :unauthorized
    else
      if @user.mobile_verified?
        if email_authentication?(params)
          if @user && @user.valid_password?(params[:user][:password])
            # debugger
            # warden.set_user(@user, scope: :user)
            # self.resource = warden.authenticate!(auth_options)
            # set_flash_message(:notice, :signed_in) if is_flashing_format?
            sign_in(@user, store: false)
            # yield resource if block_given?
            render json: @user
          else  
            render json: {error: 'Invalid Phone no / password'}, status: :unauthorized
          end
        elsif phone_authentication?(params)
            if @user && @user.valid_password?(params[:user][:password])
              render json: @user
            else
              render json: {error: 'Invalid Phone no / password'}, status: :unauthorized    
            end
        else
          render json: {error: 'Email is invalid'}, status: :unauthorized
        end
      else  
        render json: {error: 'Phone no is not verified'}, status: :unauthorized
      end
    end
  end

  def destroy
    unless all_signed_out?
      Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
      yield if block_given?
      render body: 'Logout Successfully', status: json_status(true)
    else
      render body: 'User Already Logged out', status: json_status(true)
    end
  end

  def require_no_authentication
  end

  private

  def make_phone_number params
    dialing_code = Country.find_by_dialing_code(params[:user][:country]).try(:dialing_code)
    
    # if dialing_code.present?
    #   params[:user][:email] = dialing_code + params[:user][:email].strip
    # end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/confirmation
  def create
    self.resource = resource_class.send_confirmation_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message!(:notice, :confirmed)
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
  end

  protected

    # The path used after resending confirmation instructions.
    def after_resending_confirmation_instructions_path_for(resource_name)
      is_navigational_format? ? new_session_path(resource_name) : '/'
    end

    # The path used after confirmation.
    def after_confirmation_path_for(resource_name, resource)
      if signed_in?(resource_name)
        signed_in_root_path(resource)
      else
        new_session_path(resource_name)
      end
    end

    def translation_scope
      'devise.confirmations'
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Already have an account? SIGN IN", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Create new account", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%# if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%# link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<%# end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_registration_form.html.erb
<div class="form-row">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :first_name%>
  <%= f.text_field :first_name, autofocus: true,pattern:  "[A-Za-z ]{1,32}", title: "Only alphabets are allowed",required: true, autocomplete: "First name",class: "input-field", placeholder: "*First name" %>
</div>
<div class="form-row">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :last_name%>
  <%= f.text_field :last_name, autofocus: true,required: true,pattern:  "[A-Za-z ]{1,32}",title: "Only alphabets are allowed",autocomplete: "*Last name",class: "input-field", placeholder: "*Last name" %>
</div>

<div class="form-row">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :mobile%>
  <%= f.text_field :mobile , type: :tel,class: "input-field" ,placeholder:  "*Phone number" , required: true%>
</div>

<div class="form-row">
  <%= f.label :email%>
  <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "input-field" ,placeholder:  "Email" %>
</div>

<div class="form-row">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :password%>
  <%= f.password_field :password, autocomplete: "new-password", class: "input-field" ,placeholder:  "*Password" , required: true%>

</div>
<div class="form-row clearfix">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :country_id, "Country"%>
  <div class="selectCity">
    <%= f.collection_select(:country_id, Country.all, :id, :display_name,{:prompt => "*Country"}, { class: "form--control-",required: true} )%>
  </div>
</div>
<div class="form-row radio-btns">
  <span>Join as</span>
  <div class="radio">
    <%= f.radio_button :role , "3",class: "form-check-input" , value: "3" , required: true%>
    <label for="user_role_3">Cargo Owner</label>
  </div>
  <div class="radio">
    <%= f.radio_button :role ,"4", class: "form-check-input" , value: "4", required: true%>
    <label for="user_role_4">Fleet Owner</label>
  </div>
</div>
<div class="form-row radio-btns">
  <span>I am a/an</span>
  <%= f.fields_for :company do |f| %>
      <div class="radio">
        <%= f.radio_button :company_type,:Individual, class: "form-check-input" , required: true%>
        <%= f.label :Individual ,class: "-form-check-label", for: "user_company_attributes_company_type_individual"%>
      </div>
      <div class="radio">
        <%= f.radio_button :company_type,:Company, class: "form-check-input" , required: true%>
        <%= f.label :company_type,:Company, class: "-form-check-label" , for: "user_company_attributes_company_type_company"%>
      </div>
  <%end%>
</div>
<div class="form-row">
  <div class="checkbox checkbox-success">
    <%= f.check_box  :terms_accepted , class: "styled" ,id: "user_terms_accepted" , required: true%>
<!--    <input id="checkbox3" class="styled" type="checkbox" , name="" required>-->
    <label for="user_terms_accepted">I confirm, I am above 18 years of age and
      I agree to the <span> <%= link_to "Terms and Conditions", terms_and_conditions_dashboard_index_path %></span> and <span> <%= link_to "Privacy Policy" , privacy_policy_dashboard_index_path %></span> </label>
  </div>
</div>
<div class="form-row">
  <input type="submit" name="" value="Sign Up" class="submit-btn form-submit">
</div>
<div class="form-row1">
  <%= render "users/shared/links" %>
</div>

app/views/users/shared/_waiting_trucks.html.erb
<!-- <div class="waiting-trucks">
  <span>4,000</span> ! trucks waiting to take your cargo
</div> -->