config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  resources :blogs, except: [:destroy]

  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up
    end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received

    resources :pages
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :vehicle_types, except: [:destroy]
    resources :blogs, except: [:destroy]
    resources :locations
    resources :change_destination_requests
    resources :shipments do
      member do
        delete :cancel
      end
      collection do
        post :get_bulk_coordinates
      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do
    collection do   
    post :get_all_drivers
  end end


    resources :payments
  end
  namespace :cargo do
    root 'dashboard#index'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :ongoing
        post :calculate_fare
        get :upcoming
        get :completed
        post :get_bulk_coordinates
      end
      member do
        get :get_coordinates
        get :cancel
        get :update_destination
        patch :update_destination
      end
    end
    resources :bids do
      member do
        post :accept
        post :reject
      end
    end
    resources :dashboard , only: [:index]
  end
  namespace :fleet do
    root 'shipments#posted'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :active
        get :ongoing
        get :won
        get :completed
      end
      member do
        get :quit_bid
        get :assign_vehicle
        get :cancel
        get :get_coordinates
        post :not_interested
      end
      resources :bids do
        collection do
          post :bid_details
          get :bidNow
          # get :notInterested
        end
      end
    end
    
    resources :drivers do
      collection do
        post :register_as_driver
      end
    end
    resources :vehicles do
      collection do
        get :vehicle_types
     
    end
      member do
        post :change_driver
        get :change_driver
      end
    end

    resources :dashboard , only: [:index]
  end
  resources :countries do
    collection do
      get "location/:location_id" => "countries#location"
      get :get_vehicles_by_country
      # get :vehicles
    end
  end
  devise_for :users, controllers: {:invitations => 'users/invitations',passwords: 'users/passwords', sessions: 'users/sessions', registrations: 'users/registrations',confirmations: 'users/confirmations'   }

  devise_scope :user do
    # match "user/account" => "user#account", as: :user_account, via: [:get, :post]
    match '/users/mobile-verification' => 'users/registrations#mobile_verification' , via: [:get, :post]
    get '/users/send-verification-code/:user_id' => 'users/registrations#send_verification_code', as: :send_verification_code
    match '/sign_up' => "users/registrations#new", as: :sign_up,via: [:get, :post]
  end

  resources :companies, :only => [  ] do
    collection do
      post :add_company_information
      patch :add_company_information
      post :add_individual_information
      patch :add_individual_information
      get :edit
      get :get_individual_information
      get :get_company_information
      put :presign_upload
    end
  end
  match "/ratings" => "rating#rate", via: [:get, :post] , as: :ratings_shipment
  resources :invoices , only: [:show]

  namespace :api do
  	namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions', registrations: 'api/v1/users/registrations'  }
      resources :ratings do
      end
      resources :invoices do
        member do
          post :send_in_email
        end
      end
      namespace :cargo do
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :ongoing
              get :upcoming
              post :calculate_fare
              get :completed
            end
            resources :bids do
              member do
                post :accept
                post :reject
              end
            end
          end
        end
      end
      namespace :fleet do
        resources :drivers do
          collection do
            post :register_as_driver
            post :upcoming_shipments
            post :ongoing_shipments
            post :completed_shipments
            post :update_vehicle_status
            post :report_problem
            post :payment_received
          end
        end
        resources :vehicles do
          collection do
            get :vehicle_types
            post :change_driver
            get :fetch_nearby
          end
          member do
            put :update_lat_lng
          end
        end
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :active
              get :won
              get :ongoing
              get :ongoing_vehicles
              get :completed

            end
            member do
              post :reject_bid
              post :quit_bid
              put :update_destination
              get :vehicles
              post :not_interested
            end
          resources :bids do
            collection do
              get :bidNow
              get :notInterested
            end
          end
          end
        end
      end
	  	resources :companies, :only => [] do
        collection do
          post :add_company_information
          post :add_individual_information
          get :get_individual_information
          get :get_company_information
        end
      end
      resources :countries do
        member do
          get :locations
          get :vehicles
        end
      end
      resources :reports do
        collection do
          post :logs_report
        end
      end
      resources :email do
        collection do
          post :send_shipment_email
        end
      end
      resources :signed_urls do
        collection do
          put :presign_upload
        end
      end
      resources :users, :only => [:update, :destroy] do
        collection do
          post :send_phone_verify_code
          put :verify_phone_number
          post :resent_code

          post :register_as_fleet_owner
          post :register_as_cargo_owner
          post :register_as_individual
          post :register_as_company
          post :current_user_detail
          post :db_device_id
          post :reset_password
          patch :change_online_status
          patch :change_device_id
        end
        member do
          get :notifications
        end
      end
      get 'shipments/:shipment_id/get_bids_count', to: 'fleet/bids#get_bids_count'
    end
  end
  resources :notifications , only: [] do
    collection do
      post :mark_viewed
    end
  end
  resources :users
  resources :subscriptions
  resources :dashboard  , only: [:index] do
    collection do
      get :home
      post :home_shipment
      post :share_iphone
      post :share_android
      post :contact
      get  :privacy_policy
      get  :terms_and_conditions
    end
  end

 resources :pages
  # get "/del" => "company#del"
  root 'dashboard#home'
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::V1::ApiController
  

  def add_company_information
    update_information
  end
  
  def add_individual_information
    update_information
  end

  def update_information
    if password_update_request?
      updated = validate_and_update_password
      if updated == true 
        send "#{params[:action]}_detail" 
      else
       return updated
      end
    else
      send "#{params[:action]}_detail"
    end
  end

  def validate_and_update_password
    if password_update_request? 
      password_match? ? update_password : render_response("Confirm password does not match")
    end
  end
  def get_individual_information
    @info = @user.company.individual_information
    render :json => @info 
  end

  def get_company_information
    @info =  @user.company.company_information
    render :json => @info
  end

  private
    def company_params
      params.require(:company_informations).permit(:name,:address,:landline_no,:website_address,:license_number,:license_expiry_date,:secondary_contact_name,:secondary_mobile_no,:news_update,:password,:confirm_password,:current_password,:avatar,:tax_registration_no,{documents: []})
    end

    def individual_params
      params.require(:individual_informations).permit(:secondary_mobile_no,:landline_no,:national_id,:expiry_date,:news_update,:password,:confirm_password,:current_password,:tax_registration_no,:avatar,{documents: []})  
    end

  def password_valid?
    @user.valid_password?(request_params[:current_password])
  end

  def password_update_request?
    true if request_params[:password].present? or request_params[:confirm_password].present?
  end

  def password_match?
    request_params[:password] == request_params[:confirm_password] 
  end

  def render_response(msg)
    render json: {error: msg}   
  end

  def update_password
    if request_params[:password].length >= 8
      @user.password = request_params[:password]
      @user.save
    else
      render_response("Passwords must be at least 8 characters long")
    end
    
  end

  def add_company_information_detail
    @company = current_user.company
    update_tax_registration_no

    if company_information?
      @company.company_information.update(information_params)
      render_company_json(true)
    else
      @company.build_company_information(information_params)
      @company.save
     render_company_json()

    end
    
  end

  def add_individual_information_detail
    @company = current_user.company
    update_tax_registration_no
    if individual_information?
      @company.individual_information.update(information_params)
      render_individual_json(true)
    else
      @company.build_individual_information(information_params)
      @company.save
      render_individual_json()
    end
  end


  def update_tax_registration_no
    @user.company.update_attributes(tax_registration_no: request_params[:tax_registration_no])
  end

  def request_params
    params_type = { add_individual_information: 'individual_params', add_company_information: 'company_params' }
    eval("#{params_type[params[:action].to_sym]}")
  end

  def information_params
    request_params.except(:password,:current_password,:confirm_password,:tax_registration_no)
  end

  def company_information?
    @company.company_information.present?
  end

  def individual_information?
    @company.individual_information.present?
  end

  def render_company_json(update =  false)
    if update
      @msg = "Company Information updated successfully"
    else
      @msg = "Company Information added successfully"
    end

    render 'company_information'  

  end

  def render_individual_json(update = false)
    if update
      @msg = "Individual Information updated successfully"
    else
      @msg = "Company Information added successfully"
    end
    render 'individual_information'
  end

end

app/helpers/api/v1/companies_helper.rb
module Api::V1::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_attachments.html.erb
<div class = "form-group has-feedback attachment">
  <%= f.hidden_field :documents, multiple: true, class: "js-signed-upload-value"  %>
  <input type="file" class="js-signed-upload" multiple data-presign-url="<%=  presign_upload_companies_path %>" />
    <div class = "attached_files container">
    <p class="js-signed-upload-status">
      <% if f.object.documents.present? %>
        <ul class = "documents_list">
          <%f.object.documents.each do |doc|%>
              <li>
                <a target="_blank" href="<%= doc %>">
                  <span class="remove_thumbnail">x</span>
                  <img src="<%= doc %>" alt="document" class = "document_thumbnail">
                </a>
              </li>
          <%end%>
        </ul>
    <% end %>
    </p>
  </div>
</div>
<script>
  $(".remove_thumbnail").click(function (e) {
      e.preventDefault()
      value = $(this).parents(".form-group").find(".js-signed-upload-value").val()
      value = value.split(" ")
      remove_url = $(this).parents("a").attr("href")
      index = value.indexOf(remove_url)
      value.splice(index, 1)
      $(this).parents(".form-group").find(".js-signed-upload-value").val(value.join(" "))
      $(this).parents("a").addClass("hide")
  })
</script>

app/views/companies/_avatar.html.erb
<div class = "avatar12">
  <% if @info and @info.avatar.present? %>
      <div class= "">
        <%= image_tag(@info.avatar,class: "avatar" )%>
      </div>
  <%end%>
  <div class="field form-group attachment">
    <%= f.label :avatar , "Your Profile Picture"%><br>
    <%= f.hidden_field :avatar, class: "js-signed-upload-value" %>
    <input type="file" class="js-signed-upload" data-presign-url="<%=  presign_upload_companies_path %>" />
    <p class="js-signed-upload-status">

    </p>
  </div>
</div>

app/views/companies/get_company_information.html.erb
<div class="map-form-bg1 content-wrapper">
  <div class="waiting-trucks <%= @edit ==  true ? 'hide': ''%> hide">
<!--    <span>4,000</span> ! trucks waiting to take your cargo-->
  </div>
  <div class="map-form">
    <h2 class="login-box-msg"><strong><%=@info.company.category.capitalize%> Owner</strong> (Company)</h2>
   <%= form_for(@info, url: add_company_information_companies_path) do |f| %>
    <%= render partial: "/companies/avatar", locals: {f: f,  info: @info} %>
    <div class="form-row">
      <%= f.label "*" , class: "label_required"%>
      <%= f.label "Company Name", "Company Name"%>
      <%= f.text_field :name, autofocus: true,required: true, autocomplete: "Company name",class: "input-field", placeholder: "*Company name" %>

    </div>
    <div class="form-row">
      <%= f.label "*" , class: "label_required"%>
      <%= f.label "Company Address", "Company Address"%>
      <%= f.text_field :address, autofocus: true,required: true, autocomplete: "Company Address",class: "input-field", placeholder: "*Company Address" %>
    </div>

    <div class="form-row">
      <%= f.label "*" , class: "label_required"%>
      <%= f.label "Company's Landline No.", "Company's Landline No."%>
      <%= f.text_field :landline_no, autofocus: true, autocomplete: "landline_no",class: "input-field" ,placeholder:  "*Company's Landline No." , required: true%>
    </div>

    <div class="form-row">
      <%= f.label "Company's Website Address","Company's Website Address"%>
      <%= f.text_field :website_address, autocomplete: "website_address", class: "input-field" ,placeholder:  "Company's Website Address" %>
    </div>

    <div class="form-row">
      <%= f.label "*" , class: "label_required"%>
      <%= f.label "Company's License Number", "Company's License No."%>
      <%= f.text_field :license_number , autocomplete: "license_number", class: "input-field" ,placeholder:  "*Company's License Number" , required: true%>
    </div>
    <% if current_user.fleet_owner? %>
      <div class="form-row">
        <%= label_tag "company[tax_registration_no]" , "Tax Registration No." %>
        <%= text_field_tag "company[tax_registration_no]", current_user.company.tax_registration_no,autocomplete: "tax_registration_no", class: "input-field", placeholder: "Tax Registration No." %>
      </div>
    <% end %>
    <div class="form-row">
      <%= f.label "*" , class: "label_required"%>
      <%= f.label "License Expiry Date" , "License Expiry Date"%>
      <%= f.text_field :license_expiry_date , autocomplete: "license_expiry_date", class: "input-field datepicker" ,placeholder:  "*License Expiry Date" , required: true%>
    </div>

    <div class="form-row">
      <%= f.label "*" , class: "label_required"%>
      <%= f.label "Secondary Contact Person Full Name" , "Secondary Contact Person Full Name"%>
      <%= f.text_field :secondary_contact_name , autocomplete: "secondary_contact_name", class: "input-field" ,placeholder:  "*Secondary Contact Person Full Name" , required: true%>
    </div>

    <div class="form-row">
      <%= f.label "*" , class: "label_required"%>
      <%= f.label "Secondary Contact Person Mobile Number", "Secondary Contact Person Mobile No."  %>
      <%= f.text_field :secondary_mobile_no , autocomplete: "secondary_mobile_no", class: "input-field" ,placeholder:  "*Secondary Contact Person Mobile Number" , required: true%>
    </div>
    <div class="form-row">
      <label>Upload scanned copy of your License</label>
      <%= render partial: "/companies/attachments", locals: {f: f,  info: @info} %>
    </div>
    <div class="form-row">
      <div class="col-8 sign_up_terms">
        <div class="checkbox icheck">
          <label>
            <%=f.check_box :news_update , {checked: (@info.new_record? or @info.news_update?)}%>
             Please send me product updates, news, tips, events, industry insights etc. regularly.
          </label>
        </div>
      </div>
      <div class="col-4">
        <button type="submit" class="btn btn-primary btn-block btn-flat"><%= @edit == true ? "UPDATE" : "SAVE" %></button>
      </div>
    </div>

  <% end %>
  </div>
</div>

app/views/companies/get_individual_information.html.erb
<div class="content-wrapper map-form-bg1">
  <div class="waiting-trucks <%= @edit ==  true ? 'hide': ''%> hide">
<!--    <span>4,000</span> ! trucks waiting to take your cargo-->
  </div>
  <div class="map-form">
      <h2 class="login-box-msg"><strong><%=@info.company.category.try(:capitalize)%> Owner</strong> (Individual)</h2>
      <%= form_for(@info, url: add_individual_information_companies_path) do |f| %>
          <%#= render 'layouts/error_messages', object: @info %>
          <%= render partial: "/companies/avatar", locals: {f: f,  info: @info} %>
          <% if current_user.fleet_owner? %>
            <div class="form-row">
              <%= label_tag "company[tax_registration_no]", "Tax Registration No." %>
              <%= text_field_tag "company[tax_registration_no]", current_user.company.tax_registration_no, autocomplete: "tax_registration_no", class: "input-field", placeholder: "Tax Registration No." %>
            </div>
          <% end %>
          <div class="form-row">
            <%= f.label "Secondary Mobile No", "Secondary Mobile No."%>
            <%= f.text_field :secondary_mobile_no, autofocus: true, autocomplete: "secondary_mobile_no",class: "input-field", placeholder: "Secondary Mobile No" %>
          </div>
          <div class="form-row">
            <%= f.label "Landline No.", "Landline No."%>
            <%= f.text_field :landline_no, autofocus: true, autocomplete: "landline_no",class: "input-field" ,placeholder:  "Landline No." %>
          </div>
          <div class="form-row">
            <label class="label_required">* </label>
            <label> Emirates ID No.</label>
            <%= f.text_field :national_id, autocomplete: "national_id", class: "input-field" ,placeholder:  "*Emirates ID No. " , required: true%>
          </div>
          <div class="form-row">
            <%= f.label "*" , class: "label_required"%>
            <%= f.label "Expiry Date", "Expiry Date"%>
            <%= f.text_field :expiry_date , autocomplete: "datepicker expiry_date", class: "datepicker input-field" ,placeholder:  "*Expiry Date" , required: true%>            
          </div>
          <label>Upload Front & Back side of Emirates ID</label>
          <%= render partial: "/companies/attachments", locals: {f: f,  info: @info} %>
          <div class="col-12 sign_up_terms">
              <div class="checkbox icheck">
                <label>
                  <%=f.check_box :news_update , {checked: (@info.new_record? or @info.news_update?)}%>Please send me product updates, news, tips, events, industry insights etc. regularly.
                </label>
              </div>
            </div>
            <div class="col-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat"><%= @edit == true ? "UPDATE" : "SAVE" %></button>
            </div>
      <%end%>
    </div>
  </div>
</div>
</body>