config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  resources :blogs, except: [:destroy]

  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up
    end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received

    resources :pages
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :vehicle_types, except: [:destroy]
    resources :blogs, except: [:destroy]
    resources :locations
    resources :change_destination_requests
    resources :shipments do
      member do
        delete :cancel
      end
      collection do
        post :get_bulk_coordinates
      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do
    collection do   
    post :get_all_drivers
  end end


    resources :payments
  end
  namespace :cargo do
    root 'dashboard#index'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :ongoing
        post :calculate_fare
        get :upcoming
        get :completed
        post :get_bulk_coordinates
      end
      member do
        get :get_coordinates
        get :cancel
        get :update_destination
        patch :update_destination
      end
    end
    resources :bids do
      member do
        post :accept
        post :reject
      end
    end
    resources :dashboard , only: [:index]
  end
  namespace :fleet do
    root 'shipments#posted'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :active
        get :ongoing
        get :won
        get :completed
      end
      member do
        get :quit_bid
        get :assign_vehicle
        get :cancel
        get :get_coordinates
        post :not_interested
      end
      resources :bids do
        collection do
          post :bid_details
          get :bidNow
          # get :notInterested
        end
      end
    end
    
    resources :drivers do
      collection do
        post :register_as_driver
      end
    end
    resources :vehicles do
      collection do
        get :vehicle_types
     
    end
      member do
        post :change_driver
        get :change_driver
      end
    end

    resources :dashboard , only: [:index]
  end
  resources :countries do
    collection do
      get "location/:location_id" => "countries#location"
      get :get_vehicles_by_country
      # get :vehicles
    end
  end
  devise_for :users, controllers: {:invitations => 'users/invitations',passwords: 'users/passwords', sessions: 'users/sessions', registrations: 'users/registrations',confirmations: 'users/confirmations'   }

  devise_scope :user do
    # match "user/account" => "user#account", as: :user_account, via: [:get, :post]
    match '/users/mobile-verification' => 'users/registrations#mobile_verification' , via: [:get, :post]
    get '/users/send-verification-code/:user_id' => 'users/registrations#send_verification_code', as: :send_verification_code
    match '/sign_up' => "users/registrations#new", as: :sign_up,via: [:get, :post]
  end

  resources :companies, :only => [  ] do
    collection do
      post :add_company_information
      patch :add_company_information
      post :add_individual_information
      patch :add_individual_information
      get :edit
      get :get_individual_information
      get :get_company_information
      put :presign_upload
    end
  end
  match "/ratings" => "rating#rate", via: [:get, :post] , as: :ratings_shipment
  resources :invoices , only: [:show]

  namespace :api do
  	namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions', registrations: 'api/v1/users/registrations'  }
      resources :ratings do
      end
      resources :invoices do
        member do
          post :send_in_email
        end
      end
      namespace :cargo do
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :ongoing
              get :upcoming
              post :calculate_fare
              get :completed
            end
            resources :bids do
              member do
                post :accept
                post :reject
              end
            end
          end
        end
      end
      namespace :fleet do
        resources :drivers do
          collection do
            post :register_as_driver
            post :upcoming_shipments
            post :ongoing_shipments
            post :completed_shipments
            post :update_vehicle_status
            post :report_problem
            post :payment_received
          end
        end
        resources :vehicles do
          collection do
            get :vehicle_types
            post :change_driver
            get :fetch_nearby
          end
          member do
            put :update_lat_lng
          end
        end
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :active
              get :won
              get :ongoing
              get :ongoing_vehicles
              get :completed

            end
            member do
              post :reject_bid
              post :quit_bid
              put :update_destination
              get :vehicles
              post :not_interested
            end
          resources :bids do
            collection do
              get :bidNow
              get :notInterested
            end
          end
          end
        end
      end
	  	resources :companies, :only => [] do
        collection do
          post :add_company_information
          post :add_individual_information
          get :get_individual_information
          get :get_company_information
        end
      end
      resources :countries do
        member do
          get :locations
          get :vehicles
        end
      end
      resources :reports do
        collection do
          post :logs_report
        end
      end
      resources :email do
        collection do
          post :send_shipment_email
        end
      end
      resources :signed_urls do
        collection do
          put :presign_upload
        end
      end
      resources :users, :only => [:update, :destroy] do
        collection do
          post :send_phone_verify_code
          put :verify_phone_number
          post :resent_code

          post :register_as_fleet_owner
          post :register_as_cargo_owner
          post :register_as_individual
          post :register_as_company
          post :current_user_detail
          post :db_device_id
          post :reset_password
          patch :change_online_status
          patch :change_device_id
        end
        member do
          get :notifications
        end
      end
      get 'shipments/:shipment_id/get_bids_count', to: 'fleet/bids#get_bids_count'
    end
  end
  resources :notifications , only: [] do
    collection do
      post :mark_viewed
    end
  end
  resources :users
  resources :subscriptions
  resources :dashboard  , only: [:index] do
    collection do
      get :home
      post :home_shipment
      post :share_iphone
      post :share_android
      post :contact
      get  :privacy_policy
      get  :terms_and_conditions
    end
  end

 resources :pages
  # get "/del" => "company#del"
  root 'dashboard#home'
end

app/models/country.rb
class Country < ApplicationRecord
	audited

	extend Enumerize
	has_many :users
	has_many :shipments
	has_many :vehicle_types
  has_many :locations, dependent: :destroy

	validates_uniqueness_of :dialing_code

	enumerize :process, in: {:bidding => 1, :prorate => 2}, scope: true, predicates:true

  def display_name
    "#{name.try(:capitalize)} (#{dialing_code})"
	end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < AdminController
  before_action :authenticate_user!
  before_action :check_if_admin
  before_action :set_country , only: [:edit,  :update, :destroy]
  before_action :set_countries_link ,only: [:edit,  :index , :new]
  layout 'admin'
  def index
    @countries = Country.all
    respond_to do |format|
      format.html
      format.xlsx {
        start_date = params[:start_date].present? ? params[:start_date].to_date : 100.years.ago.to_date
        end_date = params[:end_date].present? ? params[:end_date].to_date : 100.years.from_now.to_date
        @countries= Country.where(created_at: start_date..end_date)
        render xlsx: 'xlsx_countries', filename: "all_countries.xlsx", disposition: 'attachment'
      }
    end
  end
  def new
    @admin_country = Country.new
  end
  def create
    set_country_params
    @admin_country = Country.new(country_params)
    if @admin_country.save
      redirect_to admin_countries_path , notice: "Country created successfully!"
    else
      render :new
    end
  end
  def edit
  end
  def update
    set_country_params
    if @admin_country.update(country_params)
      redirect_to admin_countries_path , notice: "Country updated successfully!"
    else
      render :edit
    end
  end
  def destroy
    if @admin_country.destroy
      redirect_to admin_countries_path , notice: "Country destroyed successfully"
    else
      redirect_back(fallback_location: admin_countries_path)
    end
  end
  private
  def country_params
    params.require(:country).permit(:name, :dialing_code,:short_name ,:process, :commision, :lorryz_share_tax,:fleet_owner_income_tax, :currency, :penalty_free_hours, :status, :cargo_max_amount, :cargo_max_days,:fleet_max_amount, :fleet_max_amount,:fleet_penalty_free_hours, :fleet_max_days)
  end
  def set_country
    @admin_country = Country.find(params[:id])
  end
  def set_countries_link
    @countries_link = "active"
  end
  def set_country_params
    name = params[:country][:name]
    country = ISO3166::Country.find_country_by_name(name)
    params[:country][:short_name] = country.gec
    params[:country][:dialing_code] = "+" + country.country_code.to_s rescue  ""
  end
end

app/controllers/api/v1/countries_controller.rb
class Api::V1::CountriesController < Api::V1::ApiController
  
  before_action :verify_jwt_token, except: [:index]
  before_action :set_country, only: [:show, :edit, :locations, :vehicles]
  def index
    @countries = Country.all
    render json: @countries, status: :ok
  end

  def locations
    @company = @user.company
  	@locations = @company.locations
  end

  def vehicles
	  #@vehicles = @country.vehicle_types.join(:avatar_attachment).order(:name)
    @vehicles = VehicleType.eager_load(:avatar_attachment).where(:country_id => @country.id).order(:name)
  end

  private
  def set_country
    @country = Country.find_by_id(params[:id])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # before_action :set_country, only: [:show, :edit, :locations, :vehicles]
  def index
    @countries = Country.all
    render json: @countries, status: :ok
  end


  def get_vehicles_by_country
    if params[:filter_by]
      @country = Country.find_by_name(params[:filter_by])
      # binding.pry
      if @country
        @vehicle_types = @country.vehicle_types.order(:name)    
      else
        @vehicle_types = []
      end
    end
    render json: {vehicle_types: @vehicle_types}, status: :ok
  end

  def locations
    @locations = @country.locations
  end
  def location
    @location = Location.find(params[:location_id])
    render json: {pickup_location: @location.pickup_location,
                  pickup_building_name: @location.pickup_building_name,
                  pickup_lat: @location.pickup_lat,
                  pickup_lng: @location.pickup_lng,
                  pickup_city: @location.pickup_city,
                  drop_location: @location.drop_location,
                  drop_building_name: @location.drop_building_name,
                  drop_lat: @location.drop_lat,
                  drop_lng: @location.drop_lng,
                  drop_city: @location.drop_city,
                  rate: @location.rate,
                  loading_time: @location.loading_time  ,
                  unloading_time: @location.unloading_time,
                  vehicle_type_id: @location.vehicle_type_id}
  end
  def vehicles
    @vehicles = @country.vehicle_types
  end

  private
  def set_country
    @country = Country.find_by_id(params[:id])
  end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/admin/countries/_form.html.erb
<%= render 'layouts/error_messages', object: @admin_country %>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :name, 'Name' %>
  <%= f.select :name ,options_for_select(ISO3166::Country.all_translated ,@admin_country.name),  {:prompt => "* Name" } ,class: "form-control" , required: :true, disabled: action == "Update1"%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :Process %>
  <%= f.select(:process,options_for_select( ["bidding", "prorate"], @admin_country.process), {:prompt => "*Process" } ,{class: "form-control"}  )%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :fleet_owner_income_tax, "Fleet Owner Income Tax  (%)" %>
  <%= f.text_field :fleet_owner_income_tax , class: "form-control", placeholder: "* Fleet Owner Income Tax  (%)" , required: :true%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :currency %>
  <%= f.select :currency ,options_for_select(["IQD", "AED" ,"USD","BHD","SAR","PKR","INR"], @admin_country.currency), {:prompt => "* Currency" } , class: "form-control", required: :true%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :penalty_free_hours , "Cargo penalty free hours"%>
  <%= f.text_field :penalty_free_hours , class: "form-control", placeholder: "* Penalty Free Hours" , required: :true%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :fleet_penalty_free_hours %>
  <%= f.text_field :fleet_penalty_free_hours , class: "form-control", placeholder: "* Fleet Penalty Free Hours" , required: :true%>
</div>


<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :cargo_max_amount, "Cargo max credit amount" %>
  <%= f.text_field :cargo_max_amount  , class: "form-control", placeholder: "*Cargo max credit amount" , required: :true%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :cargo_max_days, "Cargo max credit days"%>
  <%= f.text_field :cargo_max_days , class: "form-control", placeholder: "*Cargo max credit days" , required: :true%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :fleet_max_amount , "Fleet max credit amount"%>
  <%= f.text_field :fleet_max_amount  , class: "form-control", placeholder: "*Fleet max credit amount" , required: :true%>
</div>
<div class="form-group has-feedback">
  <%= f.label "*" , class: "label_required"%>
  <%= f.label :fleet_max_days, "Fleet max credit days"%>
  <%= f.text_field :fleet_max_days , class: "form-control", placeholder: "*Fleet max credit days" , required: :true%>
</div>
<div class="form-group has-feedback">
  <%= f.check_box :status , class: ""%>
  <%= f.label :status , "Active" %>
</div>
<div class="form-group has-feedback">
</div>
<div>
  <%= f.submit action, class: "btn btn-primary btn-block btn-flat"%>
</div>

app/views/admin/countries/edit.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Edit Country</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
              <%= form_for @admin_country, url: admin_country_path do |f|%>
                  <%= render partial: "form", locals: {f: f, action: "Update"}%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/countries/index.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row1">
        <div class="card-body">
          <div class = "card">
            <div class = "card-header">
              <h3 class="card-title">Countries</h3>
              <%#= render partial: "/shared/download_excel" %>
              <br>
              
              <%= link_to "Add New Country" , new_admin_country_path , class: "btn btn-flat btn-success pull-right  add_country"%>
            </div>
            <div class = "card-body">
            <table class="table table-bordered table-striped admin_listings" data-page-length='10'>
              <thead>
              <tr>
                <% columns = ["name", "status", "process", "commision","Fleet owner income tax", "currency", "penalty_free_hours","Actions"]
                   columns.each do |col|
                %>
                  <th><%= col.humanize %></th>
                <%end%>
              </tr>
              </thead>
              <tbody>
              <% @countries.each do |country|%>
                  <tr>
                    <td><%= country.try(:name) %></td>
                    <td><%= country.try(:status) == true ? "Active" : "Inactive" %></td>
                    <td><%= country.try(:process) %></td>
                    <td><%= country.try(:commision) %></td>
                   <td><%= country.try(:fleet_owner_income_tax) %></td>
                    <td><%= country.try(:currency) %></td>
                    <td><%= country.try(:penalty_free_hours) %></td>
                    <td>
                      <%= link_to "Edit", edit_admin_country_path(country), class: "block-btn btn btn-info btn-flat" %>
                    </td>
                  </tr>
              <%end%>
              </tbody>
            </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/countries/new.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Add Country</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
              <%= form_for @admin_country, url: admin_countries_path do |f|%>
                  <%= render partial: "form", locals: {f: f, action: "Create"}%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>